### ISSUE TITLE
websocket, smoothiechart: messages arrive before chart is loaded

### ISSUE THREAD

**Issue by rmandl** [geomagpy/MARTAS#3]
not only smoothiechart must wait for smoothiesettings, further program code has to wait for smoothiechart to be loaded as well.
I found a solution, but have to implement it neatly.

**Comment by rmandl** [comment]
It is meanwhile implemented, but there must be a solution found to enable "TimeFormatter"

**Comment by leonro** [comment]
I am closing this one. Enabling TimeFormatter should be opened as a new issue if still applicable
