### ISSUE TITLE
stationid as part if sensorid

### ISSUE THREAD

**Issue by rmandl** [geomagpy/MARTAS#7]
If the stationid is part of the sensorid, then the sensorid will be changed in line 339 in collector.py
As consequence there is a error message in the log file:
Different sensorids in publish address ARDIGI_8573332393935121B0A2_0001 and header ARDIGIhhkell_8573332393935121B0A2_0001 - please check - aborting

**Comment by leonro** [comment]
Should be solved by the following commit: 2d33e1651da3ac229ad889ddfb2e2523b93dcb55
Stationid is not removed any more (only as fallback and then only first occurrence). Instead the topic is split up.

**Comment by leonro** [comment]
Seems to solved as no further reply is coming. Closing...
